global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: cloud_core
    metrics_path: /metrics
    static_configs:
      - targets: ["cloud_core:9000"]

  - job_name: scanner_service
    metrics_path: /metrics
    static_configs:
      - targets: ["scanner_service:8000"]

  - job_name: driver_service
    metrics_path: /metrics
    static_configs:
      - targets: ["driver_service:8001"]

  - job_name: version_service
    metrics_path: /metrics
    static_configs:
      - targets: ["version_service:8002"]

  - job_name: monitor_service
    metrics_path: /metrics
    static_configs:
      - targets: ["monitor_service:8003"]

  - job_name: agent_service
    metrics_path: /metrics
    static_configs:
      - targets: ["agent_service:8004"]
