<#
.SYNOPSIS
    System Revamp Endpoint Agent Silent Installer for Windows (GPO / SCCM / Intune).
.PARAMETER ServerUrl
    The central fleet management server URL (e.g. https://fleet.internal.univ.edu:8080).
.PARAMETER EnrollToken
    One-time scoped enrollment token generated by the admin dashboard.
#>

param (
    [Parameter(Mandatory=$true)]
    [string]$ServerUrl,

    [Parameter(Mandatory=$true)]
    [string]$EnrollToken,

    [string]$InstallDir = "$env:ProgramFiles\SystemRevampAgent"
)

$ErrorActionPreference = "Stop"

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "   ⚡ System Revamp Endpoint Agent Installer (Windows)" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# 1. Create installation directory
if (!(Test-Path $InstallDir)) {
    New-Item -ItemType Directory -Path $InstallDir -Force | Out-Null
    Write-Host "[+] Created target directory: $InstallDir" -ForegroundColor Green
}

# 2. Copy agent binaries/scripts
$ScriptRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$AgentSource = Join-Path (Split-Path -Parent (Split-Path -Parent $ScriptRoot)) "agent"

if (Test-Path $AgentSource) {
    Copy-Item -Path $AgentSource -Destination $InstallDir -Recurse -Force
    Write-Host "[+] Copied agent package to $InstallDir" -ForegroundColor Green
}

# 3. Perform initial enrollment
Write-Host "[+] Enrolling endpoint with central server: $ServerUrl" -ForegroundColor Yellow
$EnrollCmd = "python -m agent.main enroll --server '$ServerUrl' --token '$EnrollToken'"
Invoke-Expression $EnrollCmd

# 4. Trigger initial inventory scan
Write-Host "[+] Executing initial baseline telemetry scan..." -ForegroundColor Yellow
$ScanCmd = "python -m agent.main scan"
Invoke-Expression $ScanCmd

Write-Host "[✓] System Revamp Agent successfully installed and enrolled!" -ForegroundColor Green
